apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone
spec:
  selector:
    matchLabels:
      app: reddit-clone
  template:
    metadata:
      labels:
        app: reddit-clone
    spec:
      containers:
      - name: reddit-app
        image: deepch98/reddit-clone
        ports:
        - containerPort: 3000
